build_requires:
- build-essential
- devscripts
- fakeroot
- debhelper
- dpkg-dev
- perl
- libperl-dev
- libipc-run-perl
- libssl-dev
- zlib1g-dev
- libxml2-dev
- libxml2-utils
- libselinux1-dev
- libxslt1-dev
- uuid-dev
- python-dev
- python3-dev
- bison
- flex
- m4
- docbook-dsssl
- docbook-xml
- docbook-xsl
- docbook
- opensp
- xsltproc
- gettext
- systemtap-sdt-dev
- libssl-dev
- libgss-dev
- automake
- autotools-dev
- autoconf
- libtool
image: ubuntu:trusty
name: debian-builder
namespace: builder
version: 0.0.1
volume: /build
